version: "3.9"
services:
  nginx:
    container_name: nginx
    build: ./services/nginx
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}

  frontend:
    container_name: frontend
    user: "${UID}:${GID}"
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
      args:
        - "PORT=${FRONTEND_PORT}"
    volumes:
      - ./services/frontend:/app
  
  backend:
    container_name: backend
    user: "${UID}:${GID}"
    build: ./services/backend/
    volumes:
      - ./services/backend:/app
    depends_on:
      - postgres
    environment:
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PORT: ${DB_PORT}
      DB_PASS: ${DB_PASS}
      DB_DIALECT: ${DB_DIALECT}
      PORT: ${BACKEND_PORT}
      SECRET_TOKEN: ${JWT_SECRET_TOKEN}
  
  postgres:
    container_name: postgres
    user: "${UID}:${GID}"
    image: postgres:15.3
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}